name: 3-2

on:
  workflow_dispatch:

jobs:
  say-hello1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "auitear1"

  say-hello2:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello from python")
        shell: python
    