name: 3-3 [needs]

on:
  workflow_dispatch:

jobs:
  s-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "1"
      - run: echo "2"
      - run: echo "3"
  
  s-2:
    runs-on: ubuntu-latest
    steps:
      - run : echo "4"
      - run : echo "5"
  
  s-3:
    runs-on: ubuntu-latest
    needs:
      - s-1
      - s-2
    steps:
      - run : echo "wait s1 and s-2"
  
  s-4:
    runs-on : ubuntu-latest
    needs:
      - s-3
    steps:
      - run : echo "finish"
    

  #needs คือรอ งานที่ need ใหเสร๋จก่อนค่อยทำ

    
