name: 3-5 env

on:
  workflow_dispatch:

env:
  workflow_soi: I biggest

jobs:
  job-1:
    runs-on: ubunto-latest
    env:
      job_soi: I middle big
    steps:
      - name: job1-1
        env:
          step_soi: I smallest
        run:
          echo "sawatdee:${workflow_soi}"
          echo "sawatdee:${job_soi}"
          echo "sawatdee:${step_soi}"
  job-2:
    runs-on: ubunto-latest
    steps:
      - name: job2-1
        run:
          echo "sawatdee:${workflow_soi}"
          echo "sawatdee:${job_soi}"
          echo "sawatdee:${step_soi:-<UNSET>}"
  
