name: 3-5 env

on:
  workflow_dispatch:

env:
  workflow_soi: I biggest  #run ระดับ workflow รันได้ทุก jobs

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      job_soi: I middle big   #run ระดับ jobs ได้เฉพาะ jobs นี้เช่น jobs 1 อย่างเดียว
    steps:
      - name: job1-1
        env:
          step_soi: I smallest   #run ระดับ steps ใช้ได้แค่ job1-1
        run:
          echo "sawatdee:${workflow_soi}"
          echo "sawatdee:${job_soi}"
          echo "sawatdee:${step_soi:-<UNSET>}"
      - name: job1-2
        run:
          echo "sawatdee:${workflow_soi}"
          echo "sawatdee:${job_soi}"
          echo "sawatdee:${step_soi:-<UNSET>}"  # :- <unset>  คือถ้าไม่มีค่า ${stepsoi} ให้โชว <unset แทน>
    
    
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: job2-1
        run:
          echo "sawatdee:${workflow_soi}"
          echo "sawatdee:${job_soi}"
          echo "sawatdee:${step_soi:-<UNSET>}"
  
